name: Register repo with glossary sync

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-glossary:
    runs-on: ubuntu-latest

    env:
      REPO_OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}
      WORKFLOW_FILE: .github/workflows/register_glossary.yml

    steps:
      - name: Checkout glossary repo
        uses: actions/checkout@v4
        with:
          repository: andstor/glossary
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: glossary

      - name: Check if repository is already in matrix
        id: check_matrix
        uses: mikefarah/yq@master
        with:
          cmd: >
            yq '.jobs.sync.strategy.matrix.include[] |
              select(.repo_owner == strenv(REPO_OWNER) and .repo_name == strenv(REPO_NAME))' glossary/.github/workflows/sync.yml

      - name: Add repository to matrix if missing
        if: steps.check_matrix.outputs.result == ''
        uses: mikefarah/yq@master
        with:
          cmd: >
            yq -i '.jobs.sync.strategy.matrix.include += [{"repo_owner": strenv(REPO_OWNER), "repo_name": strenv(REPO_NAME)}]' glossary/.github/workflows/sync.yml

      - name: Commit and push changes to glossary repo
        if: steps.check_matrix.outputs.result == ''
        run: |
          cd glossary
          git config user.name "nutsbot"
          git config user.email "andr3.storhaug+bot@gmail.com"
          git add .github/workflows/sync.yml
          git commit -m "Add $REPO_NAME to glossary sync matrix"
          git push

      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Delete this workflow
        run: |
          git rm "$WORKFLOW_FILE"
          git config user.name "nutsbot"
          git config user.email "andr3.storhaug+bot@gmail.com"
          git commit -m "Remove $WORKFLOW_FILE after successful registration"
          git push
